### ISSUE TITLE
@leftside the selectd word background is too nearly leftside background to find the selected code

### ISSUE THREAD

**Issue by shynome** [sbovyrin/clean-ui-color-theme#1]
like these 
![l3_a 1jbp750o3q8e_ky ia](https://user-images.githubusercontent.com/17316043/27811212-72ab35ae-6096-11e7-9321-66c825763489.png)
![4r0a86_uqzjer_o cts d9](https://user-images.githubusercontent.com/17316043/27811717-d487012c-609b-11e7-963b-130cf08bbba2.png)

At last thank you for your so nice theme

**Comment by sbovyrin** [comment]
@shynome thanks for issue. Last update 3.1.4 should to resolve this problem.

**Comment by shynome** [comment]
![tm 6 j c9_ 8mv w8fxep8](https://user-images.githubusercontent.com/17316043/27846580-0d64fa74-616b-11e7-9668-c4364f83c9f4.png)
Its color is also nearly background

**Comment by sbovyrin** [comment]
@shynome Sorry, but I don't understand what you mean. You want to change side panel background color?

**Comment by shynome** [comment]
@sbovyrin The problem is I can't know which option has been selected . 
I'm sorry for my unclear description , it make you spend more time .

**Comment by sbovyrin** [comment]
@shynome check out updated version `3.1.5`

**Comment by shynome** [comment]
Thanks
